Move iOS mocks to Github repo
DolbyIO/comms-sdk-flutter pull request #214
Opened 2022-11-08 16:37 UTC by Bindu-Maharudrappa

2022-11-08 21:44 UTC, graduad requested changes

2022-11-08 21:44 UTC, graduad commented on test_app/integration_tests/ios_mocks/VoxeetSDKMock/LICENSE
> +    liability, obligation or undertaking of any kind in the name of, or on behalf of, or in any way binding upon, the other.
I do not think this file should be here.

2022-11-08 21:46 UTC, graduad submitted a review, later dismissed

2022-11-08 21:46 UTC, graduad commented on test_app/integration_tests/ios_mocks/LICENSE
> +    liability, obligation or undertaking of any kind in the name of, or on behalf of, or in any way binding upon, the other.
I do not think this file should be here.

2022-11-09 07:30 UTC, Bindu-Maharudrappa commented on test_app/integration_tests/ios_mocks/LICENSE
> +    liability, obligation or undertaking of any kind in the name of, or on behalf of, or in any way binding upon, the other.
Okay, I will remove both license files.

2022-11-10 10:33 UTC, kbetl-dlb approved these changes

2022-11-10 10:40 UTC, merged